apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux
  path: ./clusters/minikube
  prune: true
  wait: true
  targetNamespace: default